### ISSUE TITLE
Detection metrics evaluation

### ISSUE THREAD

**Issue by Lee-Jingyu** [shannanyinxiang/ViTEraser#1]
How are the detection metrics (precision, recall and F-measure) evaluated on SCUT-EnsText dataset in your paper?

**Comment by shannanyinxiang** [comment]
1. A pretrained [CRAFT](https://github.com/clovaai/CRAFT-pytorch) is adopted to detect texts in the text-erased images produced by the text removal model. Specifically, the general pretrained weights of CRAFT are used.
![image](https://github.com/shannanyinxiang/ViTEraser/assets/17792067/5c7b82fd-66fe-4f60-a0c5-e651e92a04e5)
2. Calculate the precision, recall, and f-measure between the detection results and ground truth.

**Comment by Lee-Jingyu** [comment]
Could you please provide the script to calculate the P, R, F between the detection results and ground truth? In case our approach differs from yours

**Comment by shannanyinxiang** [comment]
We use the evaluation scripts of [ICDAR 2015 Task 1](https://rrc.cvc.uab.es/?ch=4&com=mymethods&task=1).
