### ISSUE TITLE
能否只对特定的区域文本做抹除

### ISSUE THREAD

**Issue by liudatutu** [shannanyinxiang/ViTEraser#3]
首先感谢大佬开源测试代码，测试中发现其他文本抹除算法，都需要提供文字区域mask对特定区域进行抹除，请问ViTEraser怎么修改也可以只针对特定区域文本抹除（而不是整张图片文字抹除)？

**Comment by shannanyinxiang** [comment]
可以根据文本区域mask将整图擦除结果和输入图片组合起来，实现针对特定区域的文本擦除。

**Comment by liudatutu** [comment]
> 可以根据文本区域mask将整图擦除结果和输入图片组合起来，实现针对特定区域的文本擦除。

好的，感谢大佬抽空回复。
